{% set name = "biobox" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Degiacomi-Lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5c0e99b9743a71e5ed33cd24f55ab6d89206b8aee550dd55a03f3f8b5163cd2e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas
    - scipy
    - scikit-learn
test:
  imports:
    - biobox
  source_files:
    - test
  commands:
    - cd test
    - python test_biobox.py

about:
  home: https://github.com/Degiacomi-Lab/biobox
  license_file: LICENSE
  license: GPL-3.0-only
  summary: Biobox provides tools for loading, manipulating, and analysing atomistic and pseudoatomistic structures
  description: |
    Biobox provides a collection of data structures and methods for loading,
    manipulating, and analyzing atomistic and pseudoatomistic structures.
  doc_url: https://degiacomi-lab.github.io/biobox
  dev_url: https://github.com/Degiacomi-Lab/biobox

extra:
  recipe-maintainers:
    - SCMusson
    - degiacom
    - dclw29
